# Numpy exercises

In [2]:
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

# 1. Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function and write test cases for the function.

## 1.1 Implement standardization for 2D arrays.

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean and $\rho$ is the standard deviation of the array elements.

In [51]:
def standardize(X):
    # return (X - X.mean()) / X.std()
    return (X - X.mean(axis=0)) / X.std(axis=0)

x_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
x_std

array([[-0.70710678, -0.70710678],
       [ 1.41421356,  1.41421356],
       [-0.70710678, -0.70710678]])

In [55]:
x = np.arange(6).reshape(2, -1)
x.shape
print(x)
x.sum(axis=0)

[[0 1 2]
 [3 4 5]]


array([3, 5, 7])

## 1.2 Implement normalization for 2D arrays.

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

## 1.3 Implement the softmax function.
$$
x_i \mapsto \frac{\exp(x_i)}{\sum_{j=1}^n \exp(x_j)}
$$

In [68]:
X = np.arange(12).reshape(3, -1)

np.exp(X) / np.exp(X).sum(axis=1)[:, None]  #  # / np.exp(X).sum()


array([[0.0320586 , 0.08714432, 0.23688282, 0.64391426],
       [0.0320586 , 0.08714432, 0.23688282, 0.64391426],
       [0.0320586 , 0.08714432, 0.23688282, 0.64391426]])

# 2. Vectorization

Rewrite the following examples into vectorized solutions (no for loops and list comprehensions).

## 2.1 Row-wise Euclidean norm

Write a function which has one parameter, a 2D array and it returns a vector of row-wise Euclidean norms of the input. Use `numpy` operations and vectorization, avoid `for` loops. The solution below is a _bad_ solution.

In [ ]:
def rowwise_norm(X):
    def my_dot(x, y):
        result = 0.0
        for i in range(len(x)):
            result += x[i] * y[i]
        return result
    return np.array([np.sqrt(my_dot(x, x)) for x in X])

X = np.arange(5)[:, None]*np.ones((5, 3));
print(X)
print(rowwise_norm(X))
print(rowwise_norm([[1], [-1], [1], [-1]]))

## 2.2 Chessboard

Write a function which has one parameter, a positive integer $n$, and returns an $n\times n$ array of $\pm1$ values like a chessboard: $M_{i,j} = (-1)^{i+j}$.

In [ ]:
def chessboard(n):
    return np.array([[(-1)**(i + j) for j in range(n)] for i in range(n)])

chessboard(5)

# 3. Broadcast quiz

Do the following operations work and if so, what is the shape of the resulting array?
* Try to figure it out before evaluating the cell.

In [ ]:
np.ones(3) + np.ones((3,3))

In [ ]:
np.ones(3) + np.ones((4, 3))

In [ ]:
np.ones(3) + np.ones((3, 4))

In [ ]:
np.ones(3)[:, None] + np.ones((3, 4))

In [ ]:
np.ones((1, 2, 3)) + np.ones((1, 3))[:, None, :]

In [ ]:
np.ones((1, 2, 3)) + np.ones((1, 3))

Can you broadcast these arrays such that they can be added? What will be the shape of the result?

In [ ]:
np.ones((4,20,3)) + np.ones((5, 3))

# 4. Numpy advanced exercises

## 4.1 Blockmatrix

Write a function named __`blockmatrix`__ that produces the following (block) matrix:
$$
\left(\begin{array}{ccc|ccc}
 1 & & 0& 0 & \cdots & 0 \\
 & \ddots & & \vdots & & \vdots \\
  0& & 1 & 0 & \cdots & 0 \\\hline
  0 & \cdots & 0 & 1 & \cdots & 1 \\
  \vdots & & \vdots & \vdots & & \vdots \\
  0 & \cdots & 0 & 1 & \cdots & 1
\end{array}\right)
$$
The function should have 2 positive integer parameters, the size of the first square block and the size of the last square block. The other two blocks should have the appropriate size (may be rectangle).
The first block is an indentity matrix, the last is a constant $1$ matrix.
Return the resulted matrix.

Use matrix initializers: `ones`, `zeros`, `eye` and concatenation.

## 4.2 Blockmatrix from arbitrary square matrices

Write a blockmatrix function that takes any number of square matrices and returns a blockmatrix with these matrices in the diagonal.

## 4.3 Derivative

Write a function which numerically derivates a $\mathbb{R}\mapsto\mathbb{R}$ function. Use the forward finite difference.

The input is a 1D array of function values, and optionally a 1D vector of abscissa values. If not provided then the abscissa values are unit steps.

The result is a 1D array with the length of one less than the input array.

Use `numpy` operations instead of `for` loop in contrast to the solution below.

In [ ]:
def derivate(f, x=None):
    if x is None:
        x = np.arange(len(f))
    return np.array([(f[i+1] - f[i]) / (x[i+1] - x[i]) for i in range(len(x) - 1)])

derivate(np.arange(10)**2)

In [ ]:
x = np.arange(10)
plt.plot(x, x**2)
plt.plot(x[:-1], derivate(x**2, x))

## 4.4 Birthday problem

In probability theory, the birthday problem or birthday paradox concerns the probability that, in a set of n randomly chosen people, some pair of them will have the same birthday. By the pigeonhole principle, the probability reaches 100% when the number of people reaches 367 (since there are only 366 possible birthdays, including February 29). However, 99.9% probability is reached with just 70 people, and 50% probability with 23 people. These conclusions are based on the assumption that each day of the year (excluding February 29) is equally probable for a birthday. -- [Wikipedia](https://en.wikipedia.org/wiki/Birthday_problem)

Write a function that simulates this problem for variable $n$. Your function should take $n$ and an experiment count as its parameter and sample experiment count times and return the ratio of "birthday collisions" (how many times there were at least two birthdays on the same day).

Run it for different $n$ values with at least 1000 experiment count and plot the results. You can add a grid and check for the 50% probability with:

    fig, ax = plt.subplots()
    ax.plot(x)
    ax.grid()

## 4.5 Horner's method

Implement the [Horner's method](https://en.wikipedia.org/wiki/Horner%27s_method#Description_of_the_algorithm) for evaluating polynomials. The first input is a 1D array of numbers, the coefficients, from the constant coefficient to the highest order coefficent. The second input is the variable $x$ to subsitute. The function should work for all type of variables: numbers, arrays; the output should be the same type array as the input, containing the elementwise polynomial values.

In [ ]:
def horner(C, x):
    y = numpy.zeros_like(x)
    # YOUR CODE COMES HERE
    y
    return y

C = [2, 0, 1] # 2 + x^2
print(horner(C, 3))
print(horner(C, [3, 3]))
print(horner(C, numpy.arange(9).reshape((3,3))))