# Numpy

https://numpy.org/

### Numpy provides

* linear algebra, Fourier transform and random numbers,
* easy-to-use matrices, arrays, tensors,
* heavy optimization and
* C/C++/Fortran integration.

"Numpy is the MatLab of python!"

### import as `np` by convenction

In [2]:
import numpy as np

Numpy uses an underlying [BLAS](http://www.netlib.org/blas/) library, just as MatLab does. These libraries employ vectorization.
* Anaconda uses IntelMKL (Intel's proprietary math library)
* If you install numpy manually, and you have previously installed [OpenBLAS](http://www.openblas.net/) (free, opensource), then numpy will use that.

In [2]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


# N-dimensional arrays

The core object of `numpy` is the `ndarray` (_$n$-dimensional array_).

In [3]:
A = np.array([[[1, 2], [3, 4], [5, 6]]])
print(type(A))
A

<class 'numpy.ndarray'>


array([[[1, 2],
        [3, 4],
        [5, 6]]])

`A.shape` is a tuple of the array's dimensions

In [4]:
A.shape

(1, 3, 2)

and `dtype` is the type of the elements

In [5]:
A.dtype

dtype('int64')

In [6]:
A = np.array([1.5, 2])
A.dtype

dtype('float64')

## Accessing elements

Arrays are zero-indexed.

#### accessing one row

In [7]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A[0], A[1]

(array([1, 2]), array([3, 4]))

#### one column

In [8]:
A[:, 0]

array([1, 3, 5])

#### single element

In [9]:
A[2, 1], type(A[2, 1])

(6, numpy.int64)

#### range of rows / columns

In [10]:
A[:2]  # or A[:2, :]

array([[1, 2],
       [3, 4]])

In [11]:
A[:, 1:]

array([[2],
       [4],
       [6]])

In [12]:
A[::2]

array([[1, 2],
       [5, 6]])

In general, an $n$-dimensional array requires $n$ indices to access its scalar elements.

In [13]:
B = np.array([[[1, 2, 3],[4, 5, 6]]])
B.shape, B.ndim

((1, 2, 3), 3)

In [14]:
B[0].shape

(2, 3)

In [15]:
B[0, 1], B[0, 1].shape

(array([4, 5, 6]), (3,))

3 indices access scalar members if ndim is 3

In [16]:
B[0, 1, 2], type(B[0, 1, 2])

(6, numpy.int64)

## Under the hood

The default array representation is C style ([row-major](https://en.wikipedia.org/wiki/Row-_and_column-major_order)) indexing. But you shouldn't rely on the representation, it is not recommended to use the low level C arrays.

In [17]:
print(B.strides)
print(B.flags)

(48, 24, 8)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


# Operations on arrays

## Element-wise arithmetic operators

Arithmetic operators are overloaded, they act element-wise.

In [18]:
A = np.array([[1, 1], [2, 2]])
P = A >= 2
print(P)
print(P.dtype)

[[False False]
 [ True  True]]
bool


In [19]:
A + A

array([[2, 2],
       [4, 4]])

In [20]:
A * A

array([[1, 1],
       [4, 4]])

In [21]:
np.exp(A)

array([[2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 ]])

In [22]:
2**A

array([[2, 2],
       [4, 4]])

In [23]:
1/A

array([[1. , 1. ],
       [0.5, 0.5]])

## Matrix algebraic operations

`dot` is the standard matrix product

In [24]:
A = np.array([[1, 2], [3, 4]])
A.dot(A)

array([[ 7, 10],
       [15, 22]])

inner dimensions must match

In [25]:
B = np.array([[1, 2, 3], [4, 5, 6]])
print(A.shape, B.shape)
A.dot(B)
# B.dot(A)

(2, 2) (2, 3)


array([[ 9, 12, 15],
       [19, 26, 33]])

In [26]:
A_inv = np.linalg.inv(A)
print(A_inv)

np.allclose(A_inv.dot(A), np.eye(2))

[[-2.   1. ]
 [ 1.5 -0.5]]


True

In [27]:
np.round(A_inv.dot(A), 5)

array([[1., 0.],
       [0., 1.]])

pseudo-inverse can be computed with `np.linalg.pinv`

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A_pinv = np.linalg.pinv(A)

A.dot(A_pinv).dot(A)

array([[1., 2., 3.],
       [4., 5., 6.]])

Also, there is a `matrix` class for which `*` acts as a matrix product.

In [29]:
M = np.matrix([[1, 2], [3, 4]])
print(np.multiply(M, M))
print(M * M)
print(M ** 5)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]
[[1069 1558]
 [2337 3406]]


# Casting

C types are available in `numpy`

In [30]:
P = np.array([[1.2, 1], [1.5, 0]])
print(P.dtype)
P.astype(np.int8)

float64


array([[1, 1],
       [1, 0]], dtype=int8)

In [31]:
(-P.astype(int)).astype("uint32")

array([[4294967295, 4294967295],
       [4294967295,          0]], dtype=uint32)

In [32]:
np.array([[1, 2], [3, 4]], dtype="float32")

array([[1., 2.],
       [3., 4.]], dtype=float32)

Directly converts strings to numbers

In [33]:
np.float32('-10')

-10.0

`dtype` can be specified during array creation

In [34]:
np.array(['10', '20'], dtype="float32")

array([10., 20.], dtype=float32)

#### `np.datetime64`

In [35]:
np.datetime64("2018-03-10")

numpy.datetime64('2018-03-10')

In [36]:
np.datetime64("2018-03-10") - np.datetime64("2017-12-13")

numpy.timedelta64(87,'D')

#### String arrays

In [37]:
T = np.array(['apple', 'plum'])
print(T)
print(T.shape, T.dtype, type(T))

['apple' 'plum']
(2,) <U5 <class 'numpy.ndarray'>


Fixed length character arrays:

In [38]:
T[1] = "banana"
T

array(['apple', 'banan'], dtype='<U5')

## Slicing, advanced indexing

`:` retrieves the full size along that dimension.

In [39]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print(A[0])
print(A[0, :]) # first row
print(A[:, 0])  # first column

[[1 2 3]
 [4 5 6]]
[1 2 3]
[1 2 3]
[1 4]


These are 1D vectors, neither $1\times n$ nor $n\times1$ matrices!

In [40]:
A[0, :].shape, A[:, 0].shape

((3,), (2,))

In [41]:
B = np.array([[[1, 2, 3],[4, 5, 6]]])
B.shape

(1, 2, 3)

In [42]:
print(B[:, 1, :].shape)
B[:, 1, :]

(1, 3)


array([[4, 5, 6]])

In [43]:
B[0, 1, :], B[0, 1, :].shape

(array([4, 5, 6]), (3,))

In [44]:
type(B[0, 1, 1]), B[0, 1, 1]

(numpy.int64, 5)

All python range indexing also work, like reverse:

In [45]:
print(A[:, ::-1])
print(A[::-1, :])
print(A[:, ::2])

[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[1 3]
 [4 6]]


## Advanced indexing

Advanced indexing is when the index is a list.

In [46]:
B = np.array([[[1, 2, 3], [4, 5, 6]]])
print("B shape:", B.shape)
print(B[0, 0, [0, 2]].shape)
B[0, 0, [0, 2]]

B shape: (1, 2, 3)
(2,)


array([1, 3])

first and third "column"

In [47]:
B[0, :, [0, 2]].shape

(2, 2)

third and first "column"

In [48]:
B[0, :, [2, 0]]

array([[3, 6],
       [1, 4]])

one column can be selected multiple times and the list of indices doesn't have to be ordered

In [49]:
B[0, :, [2, 0, 2, 2]]

array([[3, 6],
       [1, 4],
       [3, 6],
       [3, 6]])

### Advanced indexing theory

If indices are all lists:
<div align=center>B[$i_1$, $i_2$, $\ldots$].shape = (len($i_1$), len($i_2$), $\ldots$)</div>

The size of a particular dimension remains when the corresponding index is a colon (`:`).

If an index is a scalar then that dimension disappears from the shape of the output.

One can use a one-length list in advanced indexing. In that case, the number of dimensions remains but the size of that dimension becomes one.

In [50]:
B = np.array([[[1, 2, 3], [4, 5, 6]]])
B[:, :, 2].shape

(1, 2)

In [51]:
B[:, :, 2]

array([[3, 6]])

In [52]:
B[:, :, [2]].shape

(1, 2, 1)

In [53]:
B[:, :, [2]]

array([[[3],
        [6]]])

In [54]:
A = np.arange(20).reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
x = [0, 0, 1, 1]
y = [4, 0, 1, 2]
A[x, y]

array([4, 0, 6, 7])

## Changing shape

The shape of an array can be modified with `reshape`, as long as the number of elements remains the same. The underlying elements are unchanged and not copied in the memory.

In [56]:
B = np.array([[[1, 2, 3], [4, 5, 6]]])
print(B.shape)
print(B.reshape((2, 3)).shape)
B.reshape((2, 3))

(1, 2, 3)
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
B.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

A `ValueError` is raised if the shape is invalid:

In [58]:
# B.reshape(7)  # raises ValueError

We have a shorthand now to create arrays like B:

In [59]:
np.array(range(6)).reshape((1, 2, 3))

array([[[0, 1, 2],
        [3, 4, 5]]])

Size `-1` can be used to span the resulted array as much as it can in that dimension.

In [60]:
X = np.array(range(12)).reshape((2, -1, 2))
print("X.shape:", X.shape)
print(X)

X.shape: (2, 3, 2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


`resize` deletes elements or fills with zeros but it works only _inplace_.

In [61]:
X = np.array([[1, 2], [3, 4]])
X.resize((5, 3))
#X.resize((2, 2))
X

array([[1, 2, 3],
       [4, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

However, `np.resize` (not a member) works differently

In [62]:
X = np.array([[1, 2], [3, 4]])
np.resize(X, (5, 3))

array([[1, 2, 3],
       [4, 1, 2],
       [3, 4, 1],
       [2, 3, 4],
       [1, 2, 3]])

`X` is unchanged:

In [63]:
X

array([[1, 2],
       [3, 4]])

# Constructing arrays

Aside from manually specifying each element, there are various functions for array creation:

* `arange`: range
* `linspace`: equally divided interval
* `ones`, `ones_like`, array filled with ones
* `zeros`, `zeros_like`, array filled with zeros
* `eye`: identity matrix, only 2D

`np.ones_like()` ans `np.zeros_like()` keeps shape and `dtype`!

In [4]:
np.arange(10), np.arange(10).shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (10,))

In [65]:
np.arange(1, 21, 2).reshape(5, -1)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [66]:
np.arange(0, 1.00001, .1001)[-1]

0.9008999999999999

In [67]:
np.linspace(0, 4, 11)

array([0. , 0.4, 0.8, 1.2, 1.6, 2. , 2.4, 2.8, 3.2, 3.6, 4. ])

In [68]:
np.ones((3, 2)) * 5

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [69]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
A = np.arange(6).reshape(3, -1)
np.zeros_like(A)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [71]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.eye(4, dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

there is no `np.eye_like`, but you can use the following:

In [73]:
np.eye(*A.shape, dtype=A.dtype)

array([[1, 0],
       [0, 1],
       [0, 0]])

## Concatenation

Arrays can be concatenated along any axis as long as their shapes are compatible.

In [74]:
A = np.arange(6).reshape(2, -1)
B = np.arange(8).reshape(2, -1)

print(A.shape, B.shape)

np.concatenate((A, B, A, B), axis=1)

(2, 3) (2, 4)


array([[0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3],
       [3, 4, 5, 4, 5, 6, 7, 3, 4, 5, 4, 5, 6, 7]])

In [75]:
np.concatenate((A, B), axis=-1)  # last dimension

array([[0, 1, 2, 0, 1, 2, 3],
       [3, 4, 5, 4, 5, 6, 7]])

In [76]:
# np.concatenate((A, B), axis=0)  # axis=0 is the default

Concatenating on the first and second dimension of 2D arrays is a very common operation, there are shorthands:

In [77]:
A = np.arange(6).reshape(2, -1)
B = np.arange(8).reshape(2, -1)

In [78]:
np.hstack((A, B))

array([[0, 1, 2, 0, 1, 2, 3],
       [3, 4, 5, 4, 5, 6, 7]])

In [79]:
A = np.arange(6).reshape(-1, 2)
B = np.arange(8).reshape(-1, 2)
print(A.shape, B.shape)

np.vstack((A, B))

(3, 2) (4, 2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [80]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

`np.stack` puts the arrays next to each other along a **new** dimension

In [81]:
A.shape, np.stack((A, A, A, A)).shape

((3, 2), (4, 3, 2))

In [82]:
np.stack((A, A, A, A))

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])

Block matrix

In [83]:
np.concatenate([np.concatenate([np.ones((2,2)), np.zeros((2,2))], axis=1),
                np.concatenate([np.zeros((2,2)), np.ones((2,2))], axis=1)], axis=0)

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

## Iteration

By default, iteration takes place in the first (outermost) dimension.

In [84]:
A = np.arange(6).reshape(2, -1)
for row in A:
    print(row)

[0 1 2]
[3 4 5]


But you can slice the desired elements for a loop.

In [85]:
B = np.arange(6).reshape(1, 2, 3)

for x in B[0, 0, :]:
    print(x)

0
1
2


You can iterate through the elements themselves.

In [86]:
for a in B.flat:
    print(a)

0
1
2
3
4
5


In [87]:
for k in range(B.shape[2]):
    print(B[:, :, k])

[[0 3]]
[[1 4]]
[[2 5]]


# Broadcasting

One can calculate with uneven shaped arrays if their shapes satisfy certain requirements.

For example a $1\times 1$ array can be multiplied with matrices, just like a scalars times a matrix.

In [88]:
s = 2.0 * np.ones((1, 1))
print(s)
print(A)
s * A

[[2.]]
[[0 1 2]
 [3 4 5]]


array([[ 0.,  2.,  4.],
       [ 6.,  8., 10.]])

A one-length vector can be multiplied with a matrix:

In [89]:
print(np.ones((1,)) * A)
np.ones(()) * B

[[0. 1. 2.]
 [3. 4. 5.]]


array([[[0., 1., 2.],
        [3., 4., 5.]]])

However you cannot perform element-wise operations on uneven sized dimensions:

In [90]:
# np.ones((2,3)) + np.ones((3,2))

This behavior is defined via _broadcasting_. If an array array has a dimension of length one, then it can be _broadcasted_, which means that it can span as much as the operation requires (operation other than indexing).

In [91]:
np.arange(3).reshape((1,3)) + np.zeros((2, 3))

array([[0., 1., 2.],
       [0., 1., 2.]])

In [92]:
np.arange(3).reshape((3,1)) + np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

More than one dimension can be broadcasted at a time.

In [93]:
np.arange(3).reshape((1,3,1)) + np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]],

       [[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.]]])

### Theory

Let's say that an array has a shape `(1, 3, 1)`, which means that it can be broadcasted in the first and third dimension.
Then the index triple `[x, y, z]` accesses its elements as `[0, y, 0]`. In one word, broadcasted dimensions are omitted in indexing.

One can broadcast non-existent dimensions, like a one-dimensional array (vector) can be broadcasted together with a three dimensional array.

In terms of shapes: `(k,) + (i, j, k)` means that a vector plus a three dimensional array (of size i-by-j-by-k). The index `[i, j, k]` of the broadcasted vector degrades to `[k]`.

Let's denote the broadcasted dimensions with `None` and the regular dimensions with their size. For example shapes `(2,) + (3, 2, 2)` results the broadcast `(None, None, 2) + (3, 2, 2)`. False dimensions are prepended at the front, or in the place of 1-length dimensions.

<div align=center>`(2,) + (3, 2, 2) -> (None, None, 2) + (3, 2, 2) = (3, 2, 2)` <br>
but<br>
`(3,) + (3, 2, 2) -> (None, None, 3) + (3, 2, 2)`
</div>
and the latter is not compatible.

In [94]:
def test_broadcast(x, y):
    try:
        A = np.ones(x) + np.ones(y)
        print("Broadcastible")
    except ValueError:
        print("Not broadcastible")

test_broadcast((3, ), (3,2,2))
test_broadcast((2, ), (3,2,2))
test_broadcast((3,1,4), (3,2,1))
test_broadcast((3,1,4), (3,2,2))

Not broadcastible
Broadcastible
Broadcastible
Not broadcastible


You can force the broadcast if you allocate a dimension of length one at a certain dimension (via `reshape`) or explicitly with the keyword `None`.

In [95]:
(np.ones(3)[:, None, None] + np.ones((3,2,2))).shape

(3, 2, 2)

The result in shapes: `(3, None, None) + (3, 2, 2) = (3, 2, 2)`

In [96]:
a = np.ones(3)
b = np.ones((3, 2, 2))
s = a + b[:, :, :, None]
s.shape

(3, 2, 2, 3)

#### Example

One liner to produce a complex "grid".

In [97]:
np.arange(5)[:, None] + 1j * np.arange(5)[None, :]

array([[0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j],
       [1.+0.j, 1.+1.j, 1.+2.j, 1.+3.j, 1.+4.j],
       [2.+0.j, 2.+1.j, 2.+2.j, 2.+3.j, 2.+4.j],
       [3.+0.j, 3.+1.j, 3.+2.j, 3.+3.j, 3.+4.j],
       [4.+0.j, 4.+1.j, 4.+2.j, 4.+3.j, 4.+4.j]])

Due to the default behavior, a vector behaves as a row vector and acts row-wise on a matrix.

`(n,) -> (None, n)`

In [98]:
np.arange(5) + np.zeros((5,5))

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

We can explicitly reshape it:

In [99]:
np.arange(5).reshape(-1, 1) + np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

This behavior does not apply to non-element-wise operations, like `dot` product.

# Reductions

Sum over an axis

In [100]:
Y = np.arange(24).reshape(2,3,4)
Y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [101]:
Y.sum()  # sum every element

276

In [102]:
Y.sum(axis=0).shape

(3, 4)

In [103]:
Y.sum(axis=(0, 2)).shape

(3,)

In [104]:
A = np.arange(6).reshape(2, -1)
print(A)
A.sum(axis=0)

[[0 1 2]
 [3 4 5]]


array([3, 5, 7])

In [105]:
Y.sum(axis=-1)

array([[ 6, 22, 38],
       [54, 70, 86]])

`mean, std, var` work similarly but compute the mean, standard deviation and variance along an axis or the full array:

In [106]:
Y.mean()

11.5

In [107]:
Y.mean(axis=(2, 0))

array([ 7.5, 11.5, 15.5])

### Vector dot product

This is a vector dot product (element-wise product and then sum):

In [108]:
def my_vec_dot(x, y):
    return (np.array(x) * np.array(y)).sum()

my_vec_dot([1, 2, 3], [1, 2, 3])

14

This is a matrix dot product:

In [109]:
def my_mat_dot(x, y):
    #            sum_j           x_{i, j,  -  }             y_{  - , j, k}
    return np.sum(np.array(x)[:, :, None]*np.array(y)[None, :, :],
                  axis=1)

my_mat_dot([[1, 2], [3, 4]], [[1, 2], [3, 4]])

array([[ 7, 10],
       [15, 22]])

More about `ufunc`: https://docs.scipy.org/doc/numpy/reference/ufuncs.html

# `np.random`

Numpy has a rich random subpackage.

`numpy.random.rand` samples random `float64` numbers from $[0, 1)$ with uniform sampling.

In [110]:
np.random.rand(2, 3).astype("float16")

array([[0.5137 , 0.1495 , 0.05087],
       [0.3416 , 0.8223 , 0.935  ]], dtype=float16)

Other distributions:

In [111]:
np.random.uniform(1, 2, (2, 2))

array([[1.78320513, 1.09217452],
       [1.8830416 , 1.71109086]])

In [112]:
np.random.standard_normal(10)

array([-0.52192184, -0.44814451, -0.13326835, -0.54051325, -1.3432295 ,
        0.32954414, -1.08911846, -0.73456316,  1.90568967,  0.6444163 ])

In [113]:
np.random.normal(10, 1, size=(1,10))

array([[ 8.50145411, 11.72400406, 10.16790915, 10.28158101, 10.94659662,
        10.35802519,  9.22356797,  9.43348149,  7.86216409, 10.93767199]])

Descrete randoms:

In [114]:
import random
help(random.choice)

Help on method choice in module random:

choice(seq) method of random.Random instance
    Choose a random element from a non-empty sequence.



In [115]:
np.random.choice(["A", "2", "3", "4", "5", "6", "7", "8", "9",
                  "10", "J", "Q", "K"], 5, replace=True)

array(['3', '4', '4', 'K', '2'], dtype='<U2')

`choice` accepts custom probabilities:

In [116]:
np.random.choice(range(1, 7), 10,
                 p=[0.1, 0.1, 0.1, 0.1, 0.1, 0.5])

array([6, 3, 5, 5, 6, 6, 4, 3, 6, 5])

In [117]:
print(np.random.permutation(["A", "2", "3", "4", "5", "6",
                             "7", "8", "9", "10", "J", "Q", "K"]))

['6' '2' 'K' '4' 'A' '5' '10' '3' '9' 'J' 'Q' '8' '7']


`permutation` permutes the first (outermost) dimension.

In [118]:
print(np.random.permutation(np.arange(9).reshape((3, 3))))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Miscellaneous

## Boolean indexing

Selecting elements that satisfy a certain condition:

In [119]:
A = np.random.random((4, 3))
print(A.mean())
A

0.43920156659438264


array([[0.69882096, 0.70712191, 0.92262072],
       [0.81294255, 0.30847862, 0.18143335],
       [0.20765277, 0.23869658, 0.1121356 ],
       [0.58401756, 0.31489613, 0.18160205]])

Selecting elements greater than the mean of the matrix:

In [120]:
A[A > A.mean()]

array([0.69882096, 0.70712191, 0.92262072, 0.81294255, 0.58401756])

`np.where` returns the advanced indices for which the condition is satisfied (where the boolean array is `True`):

In [121]:
A[np.where(A > A.mean())]

array([0.69882096, 0.70712191, 0.92262072, 0.81294255, 0.58401756])

actually `np.where` returns the indices of elements that evaluate to nonzero

In [122]:
np.where([2, -1, 0, 5])

(array([0, 1, 3]),)

# Ordering and re-ordering

In [123]:
A = np.arange(24).reshape(4, -1)
lens = np.array([4, 6, 2, 5])

order = np.argsort(-lens)
A_ordered = A[order]

rev_order = np.argsort(order)
A_ordered[rev_order]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## `np.allclose`

In [124]:
np.allclose(np.zeros((5, 5)), 0)

True

## `np.unique`

In [125]:
np.unique((1, 2, 4, 1), return_counts=True)

(array([1, 2, 4]), array([2, 1, 1]))

More numpy stuff [here](https://github.com/juditacs/snippets/blob/master/misc/numpy_stuff.ipynb).